name: Ubuntu Unittests

on:
  push:
  #    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'poetry'
      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.2.2-0
      - uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true
      - run: poetry install -E "full" --with dev --no-interaction --no-root
      - run: |
          poetry run coverage run -m pytest ./scistag/tests
          poetry run coverage lcov -i
        env:
          AZ_TEST_SOURCE_KEY: "${{ secrets.AZ_TEST_SOURCE_KEY }}"
          TEST_RELEASE: 1
          SCISTAG_FULL_TEST: 1
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov