name: Ubuntu Unittests

on:
  push:
#    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.2.2-0
      - uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydepsn-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install -E "full" --with dev --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: |
          export TEST_RELEASE=1
          poetry run coverage run -m pytest
          poetry run coverage lcov -i
        env:
          SC_testConfig_azure_storage_testSourceConnectionKey: "${{ secrets.AzureSourceConnectionKey }}"
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov