name: Ubuntu Unittests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: tests
    steps:
      - uses: actions/checkout@v3
      - name: Poetry Installer
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.2.2
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9
          cache-dependency-path: poetry.lock
          cache: 'poetry'
      - run: poetry install -E "common cutestag" --with dev --no-interaction --no-root
        env:
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
      - run: |
          poetry run coverage run -m pytest ./scistag/tests
          poetry run coverage report
        env:
          AZ_TEST_SOURCE_KEY: "${{ secrets.AZ_TEST_SOURCE_KEY }}"
          AZ_TEST_SOURCE_SAS: "${{ secrets.AZ_TEST_SOURCE_SAS }}"
          AZ_TEST_SOURCE_SAS_INV: "${{ secrets.AZ_TEST_SOURCE_SAS_INV }}"
          TEST_RELEASE: 1
          SCISTAG_FULL_TEST: 1
      - name: Coveralls GitHub Action
        run: |
          poetry run coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}