name: Ubuntu Unittests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: tests
    steps:
      - uses: actions/checkout@v2
      - name: Poetry Installer
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.2.2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'poetry'
      - run: poetry install -E "common" --with dev --no-interaction --no-root
      - run: |
          poetry run coverage run -m pytest ./scistag/tests
          poetry run coverage lcov -i
        env:
          AZ_TEST_SOURCE_KEY: "${{ secrets.AZ_TEST_SOURCE_KEY }}"
          TEST_RELEASE: 1
          SCISTAG_FULL_TEST: 1
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov