name: Windows Unittests

on:
  push:

jobs:
  test:
    runs-on: windows-latest
    environment: tests
    steps:
      - uses: actions/checkout@v3
      - name: Poetry Installer
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.2.2
      - uses: actions/setup-python@v4.4.0
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install -E "common cutestag" --with dev --no-interaction --no-root
        env:
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
      - run: poetry run python -m scistag.addons install emojis.svg
      - run: poetry run coverage run -m pytest ./scistag/tests
        env:
          AZ_TEST_SOURCE_KEY: "${{ secrets.AZ_TEST_SOURCE_KEY }}"
          AZ_TEST_SOURCE_SAS: "${{ secrets.AZ_TEST_SOURCE_SAS }}"
          AZ_TEST_SOURCE_SAS_INV: "${{ secrets.AZ_TEST_SOURCE_SAS_INV }}"
          TEST_RELEASE: 1
          SCISTAG_FULL_TEST: 1